name=TPS25751
version=1.0.0
author=Forrest Rae
maintainer=Forrest Rae
sentence=TPS25751 USB-C PD Controller Library
paragraph=Arduino-compatible library for the TPS25751, a USB-C PD controller from Texas Instruments.
category=Device Control
url=https://github.com/forrestrae/TPS25751
includes=TPS25751.h
architectures=*
license=Apache-2.0