[platformio]
build_cache_dir = .pio/buildcache

[env]
platform = teensy
framework = arduino
monitor_speed = 115200
;monitor_filters = time
;build_flags = -DDEBUG_LEVEL_MAX=1
board = teensy40

[env:example-read-registers]
build_src_filter = +<*> +<../examples/read-registers/src>

[env:example-read-downstream-bq25798-reg]
build_src_filter = +<*> +<../examples/read-downstream-bq25798-reg/src>

[env:example-bq25798-status]
build_src_filter = +<*> +<../examples/bq25798-status/src>

[env:example-bq25798-charge-config]
build_src_filter = +<*> +<../examples/bq25798-charge-config/src>

[env:example-bq25798-telemetry]
build_src_filter = +<*> +<../examples/bq25798-telemetry/src>

[env:example-bq25798-set-charge]
build_src_filter = +<*> +<../examples/bq25798-set-charge/src>


