[platformio]
default_envs = teensy40
;build_cache_dir = .pio/buildcache

[env]
platform = teensy
framework = arduino
monitor_speed = 115200
build_flags =
    -DDEBUG_LEVEL=5
lib_deps = forrestrae/TPS25751@^1.0.0

[env:teensy41]
board = teensy41

[env:teensy40]
board = teensy40